# .github/workflows/python-app.yml
name: Python application

on:
  push:
    branches: [ main ] # lub nazwa Twojej głównej gałęzi, np. master
  pull_request:
    branches: [ main ] # lub nazwa Twojej głównej gałęzi

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"] # Możesz dostosować wersje

    steps:
    - uses: actions/checkout@v4 # Zalecana jest najnowsza wersja, np. v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Zalecana jest najnowsza wersja, np. v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Pylint
      run: |
        pylint utils.py # Sprawdź tylko plik utils.py
        # Możesz też sprawdzić wszystkie pliki: pylint $(git ls-files '*.py')
    - name: Format with Black
      run: |
        black --check .
    - name: Test with Pytest
      run: |
        pytest